import "package:shop/models/models.dart";

class ProductsApiClient {
  const ProductsApiClient();

  Future<List<Product>> getProductList() async {
    await Future.delayed(Duration(seconds: 1));
    return Product.fromHighlightJson([
      {
        "id": "aijosd9",
        "articleId": "VI004EWHSOC0",
        "brand": ClothBrand.vila,
        "category": "Платье",
        "sizes": [ClothSize.l, ClothSize.m],
        "colors": [ClothColor.black],
        "gender": ClothGender.female,
        "imageUrls": [
          "https://a.lmcdn.ru/product/V/I/VI004EWHSOC0_11211635_1_v1.jpg",
          "https://a.lmcdn.ru/product//V/I/VI004EWHSOC0_11211637_3_v1.jpg",
          "https://a.lmcdn.ru/product//V/I/VI004EWHSOC0_11211638_4_v1.jpg",
        ],
        "isPremium": false,
        "isFavorite": false,
        "isNew": true,
        "discount": 15,
        "discountPrice": 2710,
        "price": 3199,
      },
      {
        "id": "jiad72h1",
        "articleId": "VI004EWHCBY3",
        "brand": ClothBrand.vila,
        "category": "Платье",
        "sizes": [ClothSize.xs, ClothSize.s, ClothSize.m],
        "colors": [ClothColor.green],
        "gender": ClothGender.female,
        "imageUrls": [
          "https://a.lmcdn.ru/product/V/I/VI004EWHCBY3_9730328_1_v1_2x.jpg",
          "https://a.lmcdn.ru/product//V/I/VI004EWHCBY3_9730329_2_v1_2x.jpg",
          "https://a.lmcdn.ru/product//V/I/VI004EWHCBY3_9730330_3_v1_2x.jpg",
        ],
        "isPremium": false,
        "isFavorite": false,
        "isNew": true,
        "discount": 50,
        "discountPrice": 2000,
        "price": 4000,
      },
      {
        "id": "kf93jap1ls",
        "articleId": "LO019EWNZJ35",
        "brand": ClothBrand.lostInk,
        "category": "Платье",
        "sizes": [ClothSize.s],
        "colors": [ClothColor.blue],
        "gender": ClothGender.female,
        "imageUrls": [
          "https://a.lmcdn.ru/product/L/O/LO019EWNZJ35_4078048_1_v3.jpg",
          "https://a.lmcdn.ru/product//L/O/LO019EWNZJ35_4983836_2_v1.jpg",
          "https://a.lmcdn.ru/product//L/O/LO019EWNZJ35_4983837_3_v1.jpg",
        ],
        "isPremium": false,
        "isFavorite": false,
        "isNew": true,
        "discount": 50,
        "discountPrice": 3050,
        "price": 6100,
      },
      {
        "id": "jfin128ndk9",
        "articleId": "MA002EWJRRS8",
        "brand": ClothBrand.mango,
        "category": "Комбинезон",
        "sizes": [ClothSize.s, ClothSize.xl],
        "colors": [ClothColor.brown],
        "gender": ClothGender.female,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWJRRS8_11415373_1_v1.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWJRRS8_11415374_2_v1.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWJRRS8_11415375_3_v1.jpg",
        ],
        "isPremium": false,
        "isFavorite": true,
        "isNew": false,
        "discount": 0,
        "discountPrice": 0,
        "price": 3999,
      },
      {
        "id": "hmhiwnyfzi",
        "articleId": "MA285EWJHYI0",
        "sizes": [ClothSize.s, ClothSize.m, ClothSize.l],
        "colors": [ClothColor.black],
        "gender": ClothGender.female,
        "brand": ClothBrand.marselesa,
        "category": "Плащ",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 13299,
        "discountPrice": 5310,
        "discount": 60,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/A/MA285EWJHYI0_11127107_1_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA285EWJHYI0_11127108_2_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA285EWJHYI0_11127109_3_v1_2x.jpg"
        ],
      },
      {
        "id": "hzdeupma",
        "articleId": "MP002XW1G5NJ",
        "sizes": [ClothSize.xs, ClothSize.s, ClothSize.m],
        "colors": [ClothColor.brown],
        "gender": ClothGender.female,
        "brand": ClothBrand.befree,
        "category": "Комбинезон",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 3599,
        "discountPrice": 2879,
        "discount": 20,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW1G5NJ_10463273_1_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW1G5NJ_10463274_2_v1_2x.jpg",
          "https://a.lmcdn.ru/product/M/P/MP002XW1G5NJ_10463273_1_v1_2x.jpg"
        ],
      },
      {
        "id": "bhfwsm",
        "articleId": "MP002XW0FQLW",
        "sizes": [ClothSize.l, ClothSize.xl],
        "colors": [ClothColor.brown],
        "gender": ClothGender.female,
        "brand": ClothBrand.cleverWomanStudio,
        "category": "Комбинезон",
        "isPremium": false,
        "isFavorite": true,
        "isNew": false,
        "price": 7250,
        "discountPrice": 3800,
        "discount": 47,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0FQLW_10394657_1_v1.jpeg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0FQLW_10394660_2_v1.jpeg",
          "https://a.lmcdn.ru/product/M/P/MP002XW0FQLW_10394657_1_v1.jpeg"
        ],
      },
      {
        "id": "dzrmxe",
        "articleId": "MP002XW1G669",
        "sizes": [ClothSize.xs, ClothSize.l],
        "colors": [ClothColor.brown],
        "gender": ClothGender.female,
        "brand": ClothBrand.gloss,
        "category": "Комбинезон",
        "isPremium": false,
        "isFavorite": true,
        "isNew": false,
        "price": 6790,
        "discountPrice": 4400,
        "discount": 35,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW1G669_10446900_1_v1.jpeg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW1G669_10446901_2_v1.jpeg",
          "https://a.lmcdn.ru/product/M/P/MP002XW1G669_10446900_1_v1.jpeg"
        ],
      },
      {
        "id": "dtpny",
        "articleId": "MP002XW0RY4U",
        "sizes": [ClothSize.xs, ClothSize.s, ClothSize.l],
        "colors": [ClothColor.red],
        "gender": ClothGender.female,
        "brand": ClothBrand.cleverWomanStudio,
        "category": "Комбинезон",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 6670,
        "discountPrice": 6100,
        "discount": 8,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0RY4U_10812283_1_v1.jpeg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0RY4U_10812286_2_v1.jpeg",
          "https://a.lmcdn.ru/product/M/P/MP002XW0RY4U_10812283_1_v1.jpeg"
        ],
      },
      {
        "id": "oakjtiicy",
        "articleId": "MP002XW16ELB",
        "sizes": [ClothSize.m, ClothSize.l],
        "colors": [ClothColor.white, ClothColor.pink],
        "gender": ClothGender.female,
        "brand": ClothBrand.befree,
        "category": "Платье",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 1799,
        "discountPrice": 1259,
        "discount": 30,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW16ELB_11107540_1_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW16ELB_11107541_2_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW16ELB_11107542_3_v1_2x.jpg"
        ],
      },
      {
        "id": "ptgxsbr",
        "articleId": "MP002XW0QFXI",
        "sizes": [ClothSize.s, ClothSize.l],
        "colors": [ClothColor.white],
        "gender": ClothGender.female,
        "brand": ClothBrand.befree,
        "category": "Сарафан",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 1799,
        "discountPrice": 0,
        "discount": 0,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0QFXI_11170993_1_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0QFXI_11170994_2_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0QFXI_11170995_3_v1_2x.jpg"
        ],
      },
      {
        "id": "bpsbug",
        "articleId": "MP002XW0RVKI",
        "sizes": [ClothSize.l, ClothSize.m, ClothSize.s],
        "colors": [ClothColor.pink],
        "gender": ClothGender.female,
        "brand": ClothBrand.gloss,
        "category": "Сарафан",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 3590,
        "discountPrice": 2500,
        "discount": 30,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0RVKI_10781367_1_v1.jpeg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0RVKI_10781368_2_v1.jpeg",
          "https://a.lmcdn.ru/img600x866/M/P/MP002XW0RVKI_10781369_3_v1.jpeg"
        ],
      },
      {
        "id": "ecnmuucjl",
        "articleId": "MA002EWIPQY1",
        "gender": ClothGender.female,
        "sizes": [ClothSize.s, ClothSize.m, ClothSize.xl],
        "colors": [ClothColor.brown, ClothColor.black, ClothColor.pink],
        "brand": ClothBrand.mango,
        "category": "Юбка",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 6499,
        "discountPrice": 2999,
        "discount": 53,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWIPQY1_10576563_1_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWIPQY1_10576564_2_v1_2x.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWIPQY1_10576565_3_v1_2x.jpg"
        ],
      },
      {
        "id": "jdugbicrk",
        "articleId": "MA002EWIIRB3",
        "gender": ClothGender.female,
        "sizes": [ClothSize.s, ClothSize.m, ClothSize.l],
        "colors": [ClothColor.brown, ClothColor.black, ClothColor.pink],
        "brand": ClothBrand.mango,
        "category": "Блуза",
        "isPremium": false,
        "isFavorite": false,
        "isNew": false,
        "price": 2799,
        "discountPrice": 1499,
        "discount": 46,
        "imageUrls": [
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWIIRB3_10318142_1_v1.jpg",
          "https://a.lmcdn.ru/img600x866/M/A/MA002EWIIRB3_10318143_2_v1.jpg",
          "https://a.lmcdn.ru/product/M/A/MA002EWIIRB3_10318142_1_v1.jpg"
        ],
      },
    ]);
  }
}
